channels:
  - conda-forge
channel_priority: flexible
dependencies:
  - python=3.11
  - numpy
  - xarray
  - hvplot
  - rich
  - pip
  - pip:
      - pystac-client
      - odc-stac
      - dask-flood-mapper
      - eodc-connect
